config/routes.rb
Rails.application.routes.draw do

  root to: "users#index"

  devise_for :users

  get 'users', to: 'users#index'
  get 'index', to: 'users#index'
  #post "users", to: "users#creation"

  get '/visits/show', to: 'visits#show', as: :show_visit
  get '/visits/new', to: 'visits#new', as: :new_visit
  post 'visits', to: 'visits#create'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/visit.rb
class Visit < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController

  skip_before_filter :require_no_authentication
  before_filter :authenticate_user!

  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  layout 'application'

  def index
    @user = User.all
  end

end

app/controllers/visits_controller.rb
class VisitsController < ApplicationController

  layout 'application'

  def show
    @visit = Visit.all
  end

  def new
    @visit = Visit.new
  end

  def create
    @visit = Visit.create(params_visits)
    if @visit.save
      redirect_to root_path
    else
      render 'create'
    end
  end

  private
  def params_visits
    params.require(:visit).permit(:name, :date, :valoration)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/visits_helper.rb
module VisitsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Log</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <% if notice %>
    <p class="alert alert-primary"><%= notice %></p>
  <% end %>
  <% if alert %>
    <p class="alert alert-danger"><%= alert %></p>
  <% end %>
    <%= yield %>
  </body>
</html>

app/views/users/index.html.erb
<section class="text-center p-5">

  <h1>Práctica 1 DAW2</h1>
  <h3> Lista de usuarios </h3>

  <% @user.each do |user| %>
      <p> <%= user.email %> <p>
  <% end %>

  <% if user_signed_in? %>
    <%= link_to "Formulario de visitas", new_visit_path, class: "btn btn-dark"  %>
    <%= link_to "Ver visitas", show_visit_path, class: "btn btn-success"  %>
    <%= link_to "Cerrar sesión", destroy_user_session_path, method: :delete, class: "btn btn-danger" %>
  <% else %>
    <%= link_to "Iniciar sesión", new_user_session_path, class: "btn btn-dark"  %>
    <%= link_to "Registarse", new_user_registration_path, class: "btn btn-dark"  %>
  <% end %>

</section>

app/views/users/new.html.erb
<%= form_with(model: @user, local: true) do |form| %>

  <div class="row">
    <div class="col-md-6 col-xs-12">
      <div class="form-group">
        <%= form.label :name %>
        <%= form.text_field :name %>
      </div>
      <div class="form-group">
        <%= form.label :email %>
        <%= form.text_field :email %>
      </div>
      <div class="form-group">
        <%= form.label :password %>
        <%= form.password_field :password %>
      </div>
    </div>
  </div>
  <div class="d-flex justify-content-center mb-2 mt-4">
    <%= form.submit "Guardar", class: "btn btn-dark" %>
  </div>
<% end %>

app/views/visits/new.html.erb
<section class="text-center p-4">
  <%= form_with(model: @visit, local: true) do |form| %>

    <h1>Formulario para añadir datos de la visita a la web</h1>

    <div class="row mt-5">
      <div class="form-group col-12 text-center">
        <%= form.label :name, "Nombre" %>
        <%= form.text_field :name %>
      </div>
      <div class="form-group col-12 text-center">
        <%= form.label :date, "Fecha" %>
        <%= form.date_field :date %>
      </div>
      <div class="form-group col-12 text-center">
        <%= form.label :valoration, "Valoración" %>
        <%= form.text_field :valoration %>
      </div>
    </div>
    <div class="d-flex justify-content-center mb-2 mt-4">
      <%= form.submit "Guardar", class: "btn btn-dark" %>
      <%= link_to "Volver al nicio", root_path, class: "btn btn-danger ml-1"  %>
    </div>

  <% end %>

</section>

app/views/visits/show.html.erb
<section class="offset-md-1 col-md-10 col-xs-12">
  <div class="my-3 content py-3 ">

    <div class="table-responsive">
      <div class="w-100 text-center">
        <h1>Visitas registradas</h1>
        <hr class="teal accent-3 mb-4 mt-0 d-inline-block mx-auto border-dark" style="width: 200px;">
      </div>

      <table class="table table-striped">
        <thead>
        <tr>
          <th class="text-center">Nombre</th>
          <th class="text-center">Fecha</th>
          <th class="text-center">Valoración del sitio web</th>
        </tr>
        </thead>

        <% @visit.each do |visit| %>
          <tbody>
          <tr>
            <td class="text-center align-middle"> <%= visit.name %> </td>
            <td class="text-center align-middle"> <%= visit.date %> </td>
            <td class="text-center align-middle"> <%= visit.valoration %> </td>
          </tr>

          </tbody>
        <% end %>
      </table>
      <div class="text-center">
        <%= link_to "Volver al inicio", root_path, class: "btn btn-danger ml-1"  %>
      </div>
    </div>
  </div>
</section>